# Discord settings:

bot_token:
client_id:
status_message:

allowed_channel_ids: []
allowed_role_ids: []

max_text: 100000
max_images: 5
max_messages: 25
max_context_tokens: 10000
max_context_depth: 3

use_plain_responses: false


# LLM settings:

providers:
  anthropic:
    base_url: https://api.anthropic.com/v1/messages
    api_key:
  openai:
    base_url: https://api.openai.com/v1
    api_key:
  x-ai:
    base_url: https://api.x.ai/v1
    api_key:
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key:
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key:
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key:
  ollama:
    base_url: http://localhost:11434/v1
  oobabooga:
    base_url: http://localhost:5000/v1
  jan:
    base_url: http://localhost:1337/v1
  lmstudio:
    base_url: http://localhost:1234/v1

model: openai/chatgpt-4o-latest
model_summarizer: openai/gpt-4o-2024-08-06
owner_id:

extra_api_parameters:
  max_tokens: 4096
  temperature: 1.0

pre_history_system_prompt: You are an discord chatbot.


system_prompt:
